# Generated by Django 3.2.5 on 2021-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protecc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudtracker',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='whitelisttracker',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
