# Generated by Django 3.2.5 on 2021-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protecc', '0003_alter_fraudtracker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudtracker',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
